---
abstract: 'Perl extension the NewRelic Agent SDK'
author:
  - 'Philippe M. Chiasson <gozer@ectoplasm.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.72, CPAN::Meta::Converter version 2.132140'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-NewRelic
no_index:
  directory:
    - t
    - inc
requires:
  HTTP::Request: 0
  LWP: 0
version: 0.03_1
