#define STATUS_OK                      NEWRELIC_RETURN_CODE_OK
#define STATUS_OTHER                   NEWRELIC_RETURN_CODE_OTHER
#define STATUS_DISABLED                NEWRELIC_RETURN_CODE_DISABLED 
#define STATUS_INVALID_PARAM           NEWRELIC_RETURN_CODE_INVALID_PARAM
#define STATUS_INVALID_ID              NEWRELIC_RETURN_CODE_INVALID_ID
#define STATUS_TRANSACTION_NOT_STARTED NEWRELIC_RETURN_CODE_TRANSACTION_NOT_STARTED
#define STATUS_TRANSACTION_IN_PROGRESS NEWRELIC_RETURN_CODE_TRANSACTION_IN_PROGRESS 
#define STATUS_TRANSACTION_NOT_NAMED   NEWRELIC_RETURN_CODE_TRANSACTION_NOT_NAMED 
#define ROOT_SEGMENT                   NEWRELIC_ROOT_SEGMENT

/*
static const int NEWRELIC_STATUS_CODE_SHUTDOWN = 0;
static const int NEWRELIC_STATUS_CODE_STARTING = 1;
static const int NEWRELIC_STATUS_CODE_STOPPING = 2;
static const int NEWRELIC_STATUS_CODE_STARTED = 3;
*/
